version: '3.5'  

services: 
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: example
        container_name: db
        volumes:
            - database:/var/lib/postgresql/data

    frontend-example-docker: 
        image: frontend-example-docker
        build: ../frontend/
      
    backend-example-docker:
        image: backend-example-docker
        build: ../backend/
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
            - DB_USERNAME=postgres
            - DB_PASSWORD=example
            - DB_HOST=db
        depends_on: 
            - db
            - redis
    redis:
        image: redis
        restart: unless-stopped
    
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro

    
volumes: 
    database:
